/*
 * Copyright 2026 Magnus Madsen
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ca.uwaterloo.flix.language.phase.llvm

import ca.uwaterloo.flix.language.ast.LoweredAst
import ca.uwaterloo.flix.language.phase.ExportAbi
import ca.uwaterloo.flix.language.phase.ExportAbi.AbiType
import ca.uwaterloo.flix.util.ArtifactNames

import scala.collection.mutable

/**
  * Renders the typed wasm export adapter layered on top of the internal `flix:runtime/runtime` substrate.
  *
  * Public design:
  *   - exported defs are surfaced as typed methods on `api.ctx`,
  *   - suspensions and generic values are public resources owned by the `api` interface,
  *   - resumption uses per-export `resume-*` methods, matching the native export ABI more closely,
  *   - the low-level runtime scheduler/resource substrate stays internal to the adapter component.
  */
object LlvmWasmTypedExportsWriter {

  case class Entry(witName: String,
                   symbol: String,
                   defId: Long,
                   signature: ExportAbi.Signature)

  def typedComponentPath(outputPath: java.nio.file.Path, artifactName: String = ArtifactNames.DefaultBaseName): java.nio.file.Path =
    LlvmWasmDriver.wasmDirPath(outputPath).resolve(ArtifactNames.wasmTypedExportComponentFileName(artifactName))

  def typedWitDirPath(outputPath: java.nio.file.Path, artifactName: String = ArtifactNames.DefaultBaseName): java.nio.file.Path =
    LlvmWasmDriver.wasmDirPath(outputPath).resolve(ArtifactNames.wasmTypedExportWitDirName(artifactName))

  def typedComponentJsPath(outputPath: java.nio.file.Path, artifactName: String = ArtifactNames.DefaultBaseName): java.nio.file.Path =
    LlvmWasmDriver.jsOutDirPath(outputPath).resolve(ArtifactNames.wasmTypedExportComponentJsFileName(artifactName)).toAbsolutePath.normalize()

  def typedComponentTypesPath(outputPath: java.nio.file.Path, artifactName: String = ArtifactNames.DefaultBaseName): java.nio.file.Path =
    LlvmWasmDriver.jsOutDirPath(outputPath).resolve(ArtifactNames.wasmTypedExportComponentTypesFileName(artifactName)).toAbsolutePath.normalize()

  def compute(root: LoweredAst.Root): List[Entry] = {
    val exports = LlvmWasmDefs.compute(root).filter(_.isExport)
    if (exports.isEmpty) return Nil

    val used = mutable.HashSet.empty[String]

    exports.map { e =>
      val base = baseWitName(e.sym.toString)
      val witName = uniqueWitName(base, e.defId, used)
      val sig = e.defn.exportedSignature.getOrElse {
        throw new IllegalStateException(s"Missing portable export signature for '${e.sym}'.")
      }
      Entry(
        witName = witName,
        symbol = e.sym.toString,
        defId = e.defId,
        signature = sig
      )
    }
  }

  def renderPublicBindings(entries: List[Entry]): String = {
    val sb = new StringBuilder(8 * 1024)
    sb.append("package flix:exports@0.1.0;\n\n")
    sb.append(renderApiInterface(entries))
    sb.append("\n")
    sb.append("world flix {\n")
    sb.append("  import flix:sys/sys@0.1.0;\n")
    sb.append("  export api;\n")
    sb.append("}\n")
    sb.toString()
  }

  def renderAdapterBindings(entries: List[Entry]): String = {
    val sb = new StringBuilder(8 * 1024)
    sb.append("package flix:exports@0.1.0;\n\n")
    sb.append(renderApiInterface(entries))
    sb.append("\n")
    sb.append("world adapter {\n")
    sb.append("  import flix:runtime/runtime@0.1.0;\n")
    sb.append("  export api;\n")
    sb.append("}\n")
    sb.toString()
  }

  def renderAdapterImpl(entries: List[Entry]): String = {
    val sb = new StringBuilder(24 * 1024)
    sb.append("// Generated by the Flix compiler (LLVM-wasm typed export adapter)\n")
    sb.append("// NOTE: This file is generated per build from the portable export ABI schema.\n")
    sb.append("#include \"adapter.h\"\n")
    sb.append("#include \"stdlib.h\"\n")
    sb.append("\n")
    sb.append("typedef struct exports_flix_exports_api_ctx_t {\n")
    sb.append("  flix_runtime_runtime_own_ctx_t runtime_ctx;\n")
    sb.append("} exports_flix_exports_api_ctx_t;\n")
    sb.append("\n")
    sb.append("typedef struct exports_flix_exports_api_value_t {\n")
    sb.append("  flix_runtime_runtime_own_value_t runtime_value;\n")
    sb.append("} exports_flix_exports_api_value_t;\n")
    sb.append("\n")
    sb.append("typedef struct exports_flix_exports_api_suspension_t {\n")
    sb.append("  flix_runtime_runtime_own_suspension_t runtime_suspension;\n")
    sb.append("  int32_t consumed;\n")
    sb.append("} exports_flix_exports_api_suspension_t;\n")
    sb.append("\n")
    sb.append("static exports_flix_exports_api_own_value_t flix_api_wrap_value(flix_runtime_runtime_own_value_t runtime_value) {\n")
    sb.append("  exports_flix_exports_api_value_t *rep = (exports_flix_exports_api_value_t *)malloc(sizeof(exports_flix_exports_api_value_t));\n")
    sb.append("  if (rep == NULL) __builtin_trap();\n")
    sb.append("  rep->runtime_value = runtime_value;\n")
    sb.append("  return exports_flix_exports_api_value_new(rep);\n")
    sb.append("}\n")
    sb.append("\n")
    sb.append("static exports_flix_exports_api_own_suspension_t flix_api_wrap_suspension(flix_runtime_runtime_own_suspension_t runtime_suspension) {\n")
    sb.append("  exports_flix_exports_api_suspension_t *rep = (exports_flix_exports_api_suspension_t *)malloc(sizeof(exports_flix_exports_api_suspension_t));\n")
    sb.append("  if (rep == NULL) __builtin_trap();\n")
    sb.append("  rep->runtime_suspension = runtime_suspension;\n")
    sb.append("  rep->consumed = 0;\n")
    sb.append("  return exports_flix_exports_api_suspension_new(rep);\n")
    sb.append("}\n")
    sb.append("\n")
    sb.append("static flix_runtime_runtime_borrow_value_t flix_api_borrow_value(exports_flix_exports_api_borrow_value_t value) {\n")
    sb.append("  return flix_runtime_runtime_borrow_value(value->runtime_value);\n")
    sb.append("}\n")
    sb.append("\n")
    sb.append("static flix_runtime_runtime_own_suspension_t flix_api_take_suspension(exports_flix_exports_api_own_suspension_t suspension) {\n")
    sb.append("  exports_flix_exports_api_suspension_t *rep = exports_flix_exports_api_suspension_rep(suspension);\n")
    sb.append("  rep->consumed = 1;\n")
    sb.append("  return rep->runtime_suspension;\n")
    sb.append("}\n")
    sb.append("\n")
    sb.append("exports_flix_exports_api_own_ctx_t exports_flix_exports_api_constructor_ctx(void) {\n")
    sb.append("  exports_flix_exports_api_ctx_t *rep = (exports_flix_exports_api_ctx_t *)malloc(sizeof(exports_flix_exports_api_ctx_t));\n")
    sb.append("  if (rep == NULL) __builtin_trap();\n")
    sb.append("  rep->runtime_ctx = flix_runtime_runtime_new_ctx();\n")
    sb.append("  return exports_flix_exports_api_ctx_new(rep);\n")
    sb.append("}\n")
    sb.append("\n")
    sb.append("void exports_flix_exports_api_ctx_destructor(exports_flix_exports_api_ctx_t *rep) {\n")
    sb.append("  flix_runtime_runtime_ctx_drop_own(rep->runtime_ctx);\n")
    sb.append("  free(rep);\n")
    sb.append("}\n")
    sb.append("\n")
    sb.append("void exports_flix_exports_api_value_destructor(exports_flix_exports_api_value_t *rep) {\n")
    sb.append("  flix_runtime_runtime_value_drop_own(rep->runtime_value);\n")
    sb.append("  free(rep);\n")
    sb.append("}\n")
    sb.append("\n")
    sb.append("void exports_flix_exports_api_suspension_destructor(exports_flix_exports_api_suspension_t *rep) {\n")
    sb.append("  if (!rep->consumed) {\n")
    sb.append("    flix_runtime_runtime_suspension_drop_own(rep->runtime_suspension);\n")
    sb.append("  }\n")
    sb.append("  free(rep);\n")
    sb.append("}\n")
    sb.append("\n")

    runtimeBoxMethodSpecs.foreach { spec =>
      sb.append(renderBoxMethod(spec._1, spec._2))
      sb.append("\n")
    }
    runtimeUnboxMethodSpecs.foreach { spec =>
      sb.append(renderUnboxMethod(spec._1, spec._2))
      sb.append("\n")
    }

    sb.append(renderSuspensionPeekMethod())
    sb.append("\n")
    sb.append(renderSuspensionArgCountMethod())
    sb.append("\n")
    sb.append(renderSuspensionArgAsI64Method())
    sb.append("\n")
    sb.append(renderSuspensionArgAsPtrMethod())
    sb.append("\n")

    entries.foreach { e =>
      sb.append(renderCallMethod(e))
      sb.append("\n")
      sb.append(renderResumeMethod(e))
      sb.append("\n")
    }

    sb.toString()
  }

  def renderCompositionWac(): String =
    """package flix:composition;
      |
      |let base = new flix:base { ... };
      |let adapter = new flix:adapter {
      |  "flix:runtime/runtime@0.1.0": base["flix:runtime/runtime@0.1.0"],
      |};
      |
      |export adapter["flix:exports/api@0.1.0"] as "flix:exports/api@0.1.0";
      |""".stripMargin

  def renderAdapterShimC(): String =
    """// Generated by the Flix compiler (LLVM-wasm typed export adapter shim)
      |#include <stddef.h>
      |#include <stdint.h>
      |
      |static unsigned char flix_adapter_heap[1 << 20];
      |static size_t flix_adapter_heap_len = 0;
      |
      |void *malloc(size_t size) {
      |  if (size == 0) size = 1;
      |  size = (size + 7u) & ~7u;
      |  if (flix_adapter_heap_len + size > sizeof(flix_adapter_heap)) __builtin_trap();
      |  void *ptr = &flix_adapter_heap[flix_adapter_heap_len];
      |  flix_adapter_heap_len += size;
      |  return ptr;
      |}
      |
      |void free(void *ptr) {
      |  (void)ptr;
      |}
      |
      |void *realloc(void *ptr, size_t size) {
      |  if (ptr == 0) return malloc(size);
      |  return malloc(size);
      |}
      |
      |void abort(void) {
      |  __builtin_trap();
      |}
      |
      |void *memcpy(void *dst, const void *src, size_t n) {
      |  unsigned char *d = (unsigned char *)dst;
      |  const unsigned char *s = (const unsigned char *)src;
      |  for (size_t i = 0; i < n; i++) d[i] = s[i];
      |  return dst;
      |}
      |
      |void *memmove(void *dst, const void *src, size_t n) {
      |  unsigned char *d = (unsigned char *)dst;
      |  const unsigned char *s = (const unsigned char *)src;
      |  if (d < s) {
      |    for (size_t i = 0; i < n; i++) d[i] = s[i];
      |  } else if (d > s) {
      |    for (size_t i = n; i > 0; i--) d[i - 1] = s[i - 1];
      |  }
      |  return dst;
      |}
      |
      |void *memset(void *dst, int c, size_t n) {
      |  unsigned char *d = (unsigned char *)dst;
      |  for (size_t i = 0; i < n; i++) d[i] = (unsigned char)c;
      |  return dst;
      |}
      |
      |int memcmp(const void *a, const void *b, size_t n) {
      |  const unsigned char *x = (const unsigned char *)a;
      |  const unsigned char *y = (const unsigned char *)b;
      |  for (size_t i = 0; i < n; i++) {
      |    if (x[i] != y[i]) return (int)x[i] - (int)y[i];
      |  }
      |  return 0;
      |}
      |
      |size_t strlen(const char *s) {
      |  size_t n = 0;
      |  while (s[n] != 0) n++;
      |  return n;
      |}
      |""".stripMargin

  def renderFreestandingStdlibHeader(): String =
    """#ifndef FLIX_ADAPTER_STDLIB_H
      |#define FLIX_ADAPTER_STDLIB_H
      |#include <stddef.h>
      |void *malloc(size_t size);
      |void free(void *ptr);
      |void *realloc(void *ptr, size_t size);
      |void abort(void);
      |#endif
      |""".stripMargin

  def renderFreestandingStringHeader(): String =
    """#ifndef FLIX_ADAPTER_STRING_H
      |#define FLIX_ADAPTER_STRING_H
      |#include <stddef.h>
      |void *memcpy(void *dst, const void *src, size_t n);
      |void *memmove(void *dst, const void *src, size_t n);
      |void *memset(void *dst, int c, size_t n);
      |int memcmp(const void *a, const void *b, size_t n);
      |size_t strlen(const char *s);
      |#endif
      |""".stripMargin

  private val runtimeBoxMethodSpecs: List[(String, AbiType)] = List(
    "box-bool" -> AbiType.Bool,
    "box-int8" -> AbiType.Int8,
    "box-int16" -> AbiType.Int16,
    "box-int32" -> AbiType.Int32,
    "box-int64" -> AbiType.Int64,
    "box-float32" -> AbiType.Float32,
    "box-float64" -> AbiType.Float64,
    "box-string" -> AbiType.String,
    "box-bytes" -> AbiType.Bytes,
  )

  private val runtimeUnboxMethodSpecs: List[(String, AbiType)] = List(
    "unbox-bool" -> AbiType.Bool,
    "unbox-int8" -> AbiType.Int8,
    "unbox-int16" -> AbiType.Int16,
    "unbox-int32" -> AbiType.Int32,
    "unbox-int64" -> AbiType.Int64,
    "unbox-float32" -> AbiType.Float32,
    "unbox-float64" -> AbiType.Float64,
    "unbox-string" -> AbiType.String,
    "unbox-bytes" -> AbiType.Bytes,
  )

  private def renderApiInterface(entries: List[Entry]): String = {
    val sb = new StringBuilder(8 * 1024)
    sb.append("interface api {\n")
    sb.append("  use flix:runtime/runtime@0.1.0.{suspension-info};\n\n")
    sb.append("  resource value;\n")
    sb.append("  resource suspension;\n\n")

    resultTypes(entries).foreach { tpe =>
      sb.append(s"  variant ${resultVariantName(tpe)} {\n")
      tpe match {
        case AbiType.Unit => sb.append("    ok,\n")
        case _ => sb.append(s"    ok(${witTypeOf(tpe)}),\n")
      }
      sb.append("    thrown(value),\n")
      sb.append("    suspended(suspension),\n")
      sb.append("  }\n\n")
    }

    sb.append("  resource ctx {\n")
    sb.append("    constructor();\n")
    runtimeBoxMethodSpecs.foreach { case (name, tpe) =>
      sb.append(s"    $name: func(x: ${witTypeOf(tpe)}) -> value;\n")
    }
    runtimeUnboxMethodSpecs.foreach { case (name, tpe) =>
      sb.append(s"    $name: func(v: borrow<value>) -> ${witTypeOf(tpe)};\n")
    }
    sb.append("    suspension-peek: func(s: borrow<suspension>) -> suspension-info;\n")
    sb.append("    suspension-arg-count: func(s: borrow<suspension>) -> u32;\n")
    sb.append("    suspension-arg-as-i64: func(s: borrow<suspension>, idx: u32) -> value;\n")
    sb.append("    suspension-arg-as-ptr: func(s: borrow<suspension>, idx: u32) -> value;\n")

    entries.foreach { e =>
      val params = e.signature.params.zipWithIndex.map {
        case (tpe, idx) => s"a$idx: ${witTypeOf(tpe)}"
      }.mkString(", ")
      sb.append(s"    ${e.witName}: func(${params}) -> ${resultVariantName(e.signature.result)};\n")
      sb.append(s"    resume-${e.witName}: func(s: suspension, resume: borrow<value>) -> ${resultVariantName(e.signature.result)};\n")
    }

    sb.append("  }\n")
    sb.append("}\n")
    sb.toString()
  }

  private def renderBoxMethod(name: String, tpe: AbiType): String = {
    val cFuncName = s"exports_flix_exports_api_method_ctx_${cIdent(name)}"
    val paramType = adapterParamCType(tpe)
    val runtimeCall = runtimeBoxMethodName(tpe)
    s"""exports_flix_exports_api_own_value_t $cFuncName(exports_flix_exports_api_borrow_ctx_t self, $paramType x) {
       |  flix_runtime_runtime_borrow_ctx_t ctx = flix_runtime_runtime_borrow_ctx(self->runtime_ctx);
       |  return flix_api_wrap_value($runtimeCall(ctx, x));
       |}
       |""".stripMargin
  }

  private def renderUnboxMethod(name: String, tpe: AbiType): String = {
    val cFuncName = s"exports_flix_exports_api_method_ctx_${cIdent(name)}"
    val runtimeCall = runtimeUnboxMethodName(tpe)
    tpe match {
      case AbiType.String | AbiType.Bytes =>
        val resultType = if (tpe == AbiType.String) "adapter_string_t" else "adapter_list_u8_t"
        s"""void $cFuncName(exports_flix_exports_api_borrow_ctx_t self, exports_flix_exports_api_borrow_value_t v, $resultType *ret) {
           |  flix_runtime_runtime_borrow_ctx_t ctx = flix_runtime_runtime_borrow_ctx(self->runtime_ctx);
           |  $runtimeCall(ctx, flix_api_borrow_value(v), ret);
           |}
           |""".stripMargin

      case _ =>
        val resultType = adapterParamCType(tpe)
        s"""$resultType $cFuncName(exports_flix_exports_api_borrow_ctx_t self, exports_flix_exports_api_borrow_value_t v) {
           |  flix_runtime_runtime_borrow_ctx_t ctx = flix_runtime_runtime_borrow_ctx(self->runtime_ctx);
           |  return $runtimeCall(ctx, flix_api_borrow_value(v));
           |}
           |""".stripMargin
    }
  }

  private def renderSuspensionPeekMethod(): String =
    """void exports_flix_exports_api_method_ctx_suspension_peek(exports_flix_exports_api_borrow_ctx_t self, exports_flix_exports_api_borrow_suspension_t s, flix_runtime_runtime_suspension_info_t *ret) {
      |  flix_runtime_runtime_borrow_ctx_t ctx = flix_runtime_runtime_borrow_ctx(self->runtime_ctx);
      |  flix_runtime_runtime_suspension_peek(ctx, flix_runtime_runtime_borrow_suspension(s->runtime_suspension), ret);
      |}
      |""".stripMargin

  private def renderSuspensionArgCountMethod(): String =
    """uint32_t exports_flix_exports_api_method_ctx_suspension_arg_count(exports_flix_exports_api_borrow_ctx_t self, exports_flix_exports_api_borrow_suspension_t s) {
      |  flix_runtime_runtime_borrow_ctx_t ctx = flix_runtime_runtime_borrow_ctx(self->runtime_ctx);
      |  return flix_runtime_runtime_suspension_arg_count(ctx, flix_runtime_runtime_borrow_suspension(s->runtime_suspension));
      |}
      |""".stripMargin

  private def renderSuspensionArgAsI64Method(): String =
    """exports_flix_exports_api_own_value_t exports_flix_exports_api_method_ctx_suspension_arg_as_i64(exports_flix_exports_api_borrow_ctx_t self, exports_flix_exports_api_borrow_suspension_t s, uint32_t idx) {
      |  flix_runtime_runtime_borrow_ctx_t ctx = flix_runtime_runtime_borrow_ctx(self->runtime_ctx);
      |  return flix_api_wrap_value(flix_runtime_runtime_suspension_arg_as_i64(ctx, flix_runtime_runtime_borrow_suspension(s->runtime_suspension), idx));
      |}
      |""".stripMargin

  private def renderSuspensionArgAsPtrMethod(): String =
    """exports_flix_exports_api_own_value_t exports_flix_exports_api_method_ctx_suspension_arg_as_ptr(exports_flix_exports_api_borrow_ctx_t self, exports_flix_exports_api_borrow_suspension_t s, uint32_t idx) {
      |  flix_runtime_runtime_borrow_ctx_t ctx = flix_runtime_runtime_borrow_ctx(self->runtime_ctx);
      |  return flix_api_wrap_value(flix_runtime_runtime_suspension_arg_as_ptr(ctx, flix_runtime_runtime_borrow_suspension(s->runtime_suspension), idx));
      |}
      |""".stripMargin

  private def renderCallMethod(entry: Entry): String = {
    val sb = new StringBuilder(2048)
    val cFuncName = s"exports_flix_exports_api_method_ctx_${cIdent(entry.witName)}"
    val resultCType = s"exports_flix_exports_api_${cIdent(resultVariantName(entry.signature.result))}_t"
    val paramDecls = entry.signature.params.zipWithIndex.map {
      case (tpe, idx) => s"${adapterParamCType(tpe)} a$idx"
    }

    sb.append(s"void $cFuncName(exports_flix_exports_api_borrow_ctx_t self")
    if (paramDecls.nonEmpty) sb.append(", ").append(paramDecls.mkString(", "))
    sb.append(s", $resultCType *ret) {\n")
    sb.append("  flix_runtime_runtime_borrow_ctx_t ctx = flix_runtime_runtime_borrow_ctx(self->runtime_ctx);\n")
    entry.signature.params.zipWithIndex.foreach {
      case (tpe, idx) =>
        val argName = s"a$idx"
        sb.append(s"  flix_runtime_runtime_own_value_t arg$idx = ${boxExpr(tpe, argName)};\n")
    }
    if (entry.signature.params.nonEmpty) {
      sb.append(s"  flix_runtime_runtime_borrow_value_t argv[${entry.signature.params.length}];\n")
      entry.signature.params.indices.foreach { idx =>
        sb.append(s"  argv[$idx] = flix_runtime_runtime_borrow_value(arg$idx);\n")
      }
    }
    sb.append(s"  flix_runtime_runtime_list_borrow_value_t args = { ${if (entry.signature.params.nonEmpty) "argv" else "0"}, ${entry.signature.params.length} };\n")
    sb.append("  flix_runtime_runtime_exec_t exec;\n")
    sb.append(s"  flix_runtime_runtime_invoke(ctx, ${entry.defId}ULL, &args, &exec);\n")
    entry.signature.params.indices.foreach { idx =>
      sb.append(s"  flix_runtime_runtime_value_drop_own(arg$idx);\n")
    }
    sb.append(renderTranslateRuntimeExec(entry.signature.result, "exec"))
    sb.append("}\n")
    sb.toString()
  }

  private def renderResumeMethod(entry: Entry): String = {
    val sb = new StringBuilder(1024)
    val cFuncName = s"exports_flix_exports_api_method_ctx_resume_${cIdent(entry.witName)}"
    val resultCType = s"exports_flix_exports_api_${cIdent(resultVariantName(entry.signature.result))}_t"
    sb.append(s"void $cFuncName(exports_flix_exports_api_borrow_ctx_t self, exports_flix_exports_api_own_suspension_t s, exports_flix_exports_api_borrow_value_t resume, $resultCType *ret) {\n")
    sb.append("  flix_runtime_runtime_borrow_ctx_t ctx = flix_runtime_runtime_borrow_ctx(self->runtime_ctx);\n")
    sb.append("  flix_runtime_runtime_own_suspension_t runtime_s = flix_api_take_suspension(s);\n")
    sb.append("  flix_runtime_runtime_exec_t exec;\n")
    sb.append("  flix_runtime_runtime_resume_ok_sync(ctx, runtime_s, flix_api_borrow_value(resume), &exec);\n")
    sb.append(renderTranslateRuntimeExec(entry.signature.result, "exec"))
    sb.append("}\n")
    sb.toString()
  }

  private def renderTranslateRuntimeExec(resultTpe: AbiType, execVar: String): String = {
    val sb = new StringBuilder(1024)
    sb.append(s"  switch ($execVar.tag) {\n")
    sb.append("    case FLIX_RUNTIME_RUNTIME_EXEC_OK:\n")
    resultTpe match {
      case AbiType.Unit =>
        sb.append(s"      ret->tag = ${resultTag(resultTpe, "OK")};\n")
        sb.append(s"      flix_runtime_runtime_exec_free(&$execVar);\n")
        sb.append("      return;\n")
      case AbiType.String =>
        sb.append(s"      ret->tag = ${resultTag(resultTpe, "OK")};\n")
        sb.append(s"      flix_runtime_runtime_unbox_string(ctx, flix_runtime_runtime_borrow_value($execVar.val.ok), &ret->val.ok);\n")
        sb.append(s"      flix_runtime_runtime_exec_free(&$execVar);\n")
        sb.append("      return;\n")
      case AbiType.Bytes =>
        sb.append(s"      ret->tag = ${resultTag(resultTpe, "OK")};\n")
        sb.append(s"      flix_runtime_runtime_unbox_bytes(ctx, flix_runtime_runtime_borrow_value($execVar.val.ok), &ret->val.ok);\n")
        sb.append(s"      flix_runtime_runtime_exec_free(&$execVar);\n")
        sb.append("      return;\n")
      case _ =>
        sb.append(s"      ret->tag = ${resultTag(resultTpe, "OK")};\n")
        val borrowExpr = s"flix_runtime_runtime_borrow_value($execVar.val.ok)"
        sb.append(s"      ret->val.ok = ${unboxExpr(resultTpe, borrowExpr)};\n")
        sb.append(s"      flix_runtime_runtime_exec_free(&$execVar);\n")
        sb.append("      return;\n")
    }
    sb.append("    case FLIX_RUNTIME_RUNTIME_EXEC_THROWN:\n")
    sb.append(s"      ret->tag = ${resultTag(resultTpe, "THROWN")};\n")
    sb.append(s"      ret->val.thrown = flix_api_wrap_value($execVar.val.thrown);\n")
    sb.append("      return;\n")
    sb.append("    case FLIX_RUNTIME_RUNTIME_EXEC_SUSPENDED:\n")
    sb.append(s"      ret->tag = ${resultTag(resultTpe, "SUSPENDED")};\n")
    sb.append(s"      ret->val.suspended = flix_api_wrap_suspension($execVar.val.suspended.suspension);\n")
    sb.append("      return;\n")
    sb.append("    default:\n")
    sb.append("      __builtin_trap();\n")
    sb.append("  }\n")
    sb.toString()
  }

  private def resultTypes(entries: List[Entry]): List[AbiType] =
    entries.iterator.map(_.signature.result).toSet.toList.sortBy((t: AbiType) => t.displayName)

  private def resultVariantName(tpe: AbiType): String = s"exec-${witTypeTag(tpe)}"

  private def witTypeTag(tpe: AbiType): String = tpe match {
    case AbiType.Unit => "unit"
    case AbiType.Bool => "bool"
    case AbiType.Int8 => "int8"
    case AbiType.Int16 => "int16"
    case AbiType.Int32 => "int32"
    case AbiType.Int64 => "int64"
    case AbiType.Float32 => "float32"
    case AbiType.Float64 => "float64"
    case AbiType.String => "string"
    case AbiType.Bytes => "bytes"
  }

  private def witTypeOf(tpe: AbiType): String = tpe match {
    case AbiType.Unit => "tuple<>"
    case AbiType.Bool => "bool"
    case AbiType.Int8 => "s8"
    case AbiType.Int16 => "s16"
    case AbiType.Int32 => "s32"
    case AbiType.Int64 => "s64"
    case AbiType.Float32 => "f32"
    case AbiType.Float64 => "f64"
    case AbiType.String => "string"
    case AbiType.Bytes => "list<u8>"
  }

  private def adapterParamCType(tpe: AbiType): String = tpe match {
    case AbiType.Unit => "int32_t"
    case AbiType.Bool => "bool"
    case AbiType.Int8 => "int8_t"
    case AbiType.Int16 => "int16_t"
    case AbiType.Int32 => "int32_t"
    case AbiType.Int64 => "int64_t"
    case AbiType.Float32 => "float"
    case AbiType.Float64 => "double"
    case AbiType.String => "adapter_string_t *"
    case AbiType.Bytes => "adapter_list_u8_t *"
  }

  private def runtimeBoxMethodName(tpe: AbiType): String = tpe match {
    case AbiType.Bool => "flix_runtime_runtime_box_bool"
    case AbiType.Int8 => "flix_runtime_runtime_box_i8"
    case AbiType.Int16 => "flix_runtime_runtime_box_i16"
    case AbiType.Int32 => "flix_runtime_runtime_box_i32"
    case AbiType.Int64 => "flix_runtime_runtime_box_i64"
    case AbiType.Float32 => "flix_runtime_runtime_box_f32"
    case AbiType.Float64 => "flix_runtime_runtime_box_f64"
    case AbiType.String => "flix_runtime_runtime_box_string"
    case AbiType.Bytes => "flix_runtime_runtime_box_bytes"
    case other => throw new IllegalStateException(s"Unexpected box type: $other")
  }

  private def runtimeUnboxMethodName(tpe: AbiType): String = tpe match {
    case AbiType.Bool => "flix_runtime_runtime_unbox_bool"
    case AbiType.Int8 => "flix_runtime_runtime_unbox_i8"
    case AbiType.Int16 => "flix_runtime_runtime_unbox_i16"
    case AbiType.Int32 => "flix_runtime_runtime_unbox_i32"
    case AbiType.Int64 => "flix_runtime_runtime_unbox_i64"
    case AbiType.Float32 => "flix_runtime_runtime_unbox_f32"
    case AbiType.Float64 => "flix_runtime_runtime_unbox_f64"
    case AbiType.String => "flix_runtime_runtime_unbox_string"
    case AbiType.Bytes => "flix_runtime_runtime_unbox_bytes"
    case other => throw new IllegalStateException(s"Unexpected unbox type: $other")
  }

  private def boxExpr(tpe: AbiType, valueExpr: String): String = tpe match {
    case AbiType.Unit => "flix_runtime_runtime_box_i32(ctx, 0)"
    case other => s"${runtimeBoxMethodName(other)}(ctx, $valueExpr)"
  }

  private def unboxExpr(tpe: AbiType, borrowExpr: String): String = tpe match {
    case AbiType.Bool => s"flix_runtime_runtime_unbox_bool(ctx, $borrowExpr)"
    case AbiType.Int8 => s"flix_runtime_runtime_unbox_i8(ctx, $borrowExpr)"
    case AbiType.Int16 => s"flix_runtime_runtime_unbox_i16(ctx, $borrowExpr)"
    case AbiType.Int32 => s"flix_runtime_runtime_unbox_i32(ctx, $borrowExpr)"
    case AbiType.Int64 => s"flix_runtime_runtime_unbox_i64(ctx, $borrowExpr)"
    case AbiType.Float32 => s"flix_runtime_runtime_unbox_f32(ctx, $borrowExpr)"
    case AbiType.Float64 => s"flix_runtime_runtime_unbox_f64(ctx, $borrowExpr)"
    case other => throw new IllegalStateException(s"Unexpected scalar result type: $other")
  }

  private def resultTag(resultTpe: AbiType, suffix: String): String =
    s"EXPORTS_FLIX_EXPORTS_API_${cIdent(resultVariantName(resultTpe)).toUpperCase}_${suffix}"

  private def baseWitName(sym: String): String = {
    val segments = sym.split("\\.").toList.filter(_.nonEmpty)
    val raw = if (segments.isEmpty) sym else segments.mkString("-")
    raw
      .flatMap {
        case c if c.isLetterOrDigit => c.toString.toLowerCase
        case _ => "-"
      }
      .replaceAll("-{2,}", "-")
      .stripPrefix("-")
      .stripSuffix("-")
      .ensuring(_.nonEmpty, "wit export name cannot be empty")
  }

  private def uniqueWitName(base: String, defId: Long, used: mutable.Set[String]): String = {
    if (!used.contains(base)) {
      used += base
      base
    } else {
      val tagged = s"$base-$defId"
      used += tagged
      tagged
    }
  }

  private def cIdent(name: String): String =
    name.map {
      case c if c.isLetterOrDigit || c == '_' => c
      case _ => '_'
    }
}
