/*
 * Copyright 2026 Magnus Madsen
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ca.uwaterloo.flix.language.phase.llvm

import ca.uwaterloo.flix.api.Flix
import ca.uwaterloo.flix.language.phase.ExportAbi.AbiType
import ca.uwaterloo.flix.util.{ArtifactNames, InternalCompilerException}

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, LinkOption, Path}
import scala.collection.mutable

/**
  * Writes typed JavaScript/TypeScript convenience bindings for wasm `@Export` defs.
  *
  * These bindings are intentionally thin wrappers over the public typed wasm export component.
  * They do not reintroduce the internal `flix:runtime/runtime` substrate.
  */
object LlvmWasmBindingWriter {

  case class Artifacts(js: Path, dts: Path)

  def run(root: ca.uwaterloo.flix.language.ast.LoweredAst.Root)(implicit flix: Flix): Option[Artifacts] = {
    val exports = LlvmWasmTypedExportsWriter.compute(root)
    if (exports.isEmpty) return None

    val jsPath = bindingsJsPath(flix.options.outputPath, flix.options.artifactName)
    val dtsPath = bindingsTypesPath(flix.options.outputPath, flix.options.artifactName)

    writeFile(jsPath, renderJs(exports, flix.options.artifactName).getBytes(StandardCharsets.UTF_8))
    writeFile(dtsPath, renderDts(exports, flix.options.artifactName).getBytes(StandardCharsets.UTF_8))

    Some(Artifacts(jsPath, dtsPath))
  }

  def bindingsJsPath(outputPath: Path, artifactName: String = ArtifactNames.DefaultBaseName): Path =
    LlvmWasmDriver.jsOutDirPath(outputPath).resolve(ArtifactNames.wasmBindingsJsFileName(artifactName)).toAbsolutePath.normalize()

  def bindingsTypesPath(outputPath: Path, artifactName: String = ArtifactNames.DefaultBaseName): Path =
    LlvmWasmDriver.jsOutDirPath(outputPath).resolve(ArtifactNames.wasmBindingsTypesFileName(artifactName)).toAbsolutePath.normalize()

  private def renderJs(exports: List[LlvmWasmTypedExportsWriter.Entry], artifactName: String): String = {
    val sb = new StringBuilder(12 * 1024)

    sb.append("// Generated by the Flix compiler (LLVM-wasm typed export bindings)\n")
    sb.append("// NOTE: This file is a thin convenience layer over the public typed wasm export component.\n")
    sb.append(s"""import { api } from "./${ArtifactNames.wasmTypedExportComponentJsFileName(artifactName)}";\n""")
    sb.append("\n")
    sb.append("export { api };\n")
    sb.append("\n")
    sb.append("export function newCtx() {\n")
    sb.append("  return new api.Ctx();\n")
    sb.append("}\n")
    sb.append("\n")

    exports.foreach { e =>
      val jsArgs = e.signature.params.indices.map(idx => s"a$idx").toList
      val callName = flatFunctionName(e.symbol)
      val resumeName = flatResumeFunctionName(e.symbol)
      val ctxMethod = jsMethodNameFromWitName(e.witName)
      val ctxResumeMethod = jsMethodNameFromWitName(s"resume-${e.witName}")

      sb.append(s"export function $callName(ctx${if (jsArgs.nonEmpty) ", " else ""}${jsArgs.mkString(", ")}) {\n")
      sb.append(s"  return ctx.$ctxMethod(${jsArgs.mkString(", ")});\n")
      sb.append("}\n\n")

      sb.append(s"export function $resumeName(ctx, suspension, resume) {\n")
      sb.append(s"  return ctx.$ctxResumeMethod(suspension, resume);\n")
      sb.append("}\n\n")
    }

    sb.append("export const metadata = {\n")
    exports.zipWithIndex.foreach { case (e, idx) =>
      val params = e.signature.params.map(p => "\"" + p.displayName + "\"").mkString(", ")
      sb.append(s"""  "${escapeJsString(e.symbol)}": { defId: ${e.defId}n, params: [$params], result: "${e.signature.result.displayName}" }""")
      if (idx != exports.length - 1) sb.append(",")
      sb.append("\n")
    }
    sb.append("};\n\n")

    sb.append("export const Exports = ")
    sb.append(renderTree(buildTree(exports), leaf => leaf.fnName))
    sb.append(";\n")

    sb.toString()
  }

  private def renderDts(exports: List[LlvmWasmTypedExportsWriter.Entry], artifactName: String): String = {
    val sb = new StringBuilder(10 * 1024)

    sb.append("// Generated by the Flix compiler (LLVM-wasm typed export bindings)\n")
    sb.append(s"""import type * as TypedExports from "./${ArtifactNames.wasmTypedExportComponentJsFileName(artifactName)}";\n""")
    sb.append(s"""export { api } from "./${ArtifactNames.wasmTypedExportComponentJsFileName(artifactName)}";\n\n""")
    sb.append("export type FlixCtx = TypedExports.api.Ctx;\n")
    sb.append("export type FlixValue = TypedExports.api.Value;\n")
    sb.append("export type FlixSuspension = TypedExports.api.Suspension;\n\n")
    sb.append("export function newCtx(): TypedExports.api.Ctx;\n")
    sb.append("export const metadata: Record<string, { defId: bigint; params: readonly string[]; result: string }>;\n\n")

    exports.foreach { e =>
      val callName = flatFunctionName(e.symbol)
      val resumeName = flatResumeFunctionName(e.symbol)
      val args = e.signature.params.zipWithIndex.map {
        case (tpe, idx) => s"a$idx: ${tsTypeOf(tpe)}"
      }.mkString(", ")
      sb.append(s"export function $callName(ctx: TypedExports.api.Ctx${if (args.nonEmpty) ", " else ""}$args): ${tsExecTypeOf(e.signature.result)};\n")
      sb.append(s"export function $resumeName(ctx: TypedExports.api.Ctx, suspension: TypedExports.api.Suspension, resume: TypedExports.api.Value): ${tsExecTypeOf(e.signature.result)};\n")
    }
    sb.append("\n")
    sb.append("export const Exports: ")
    sb.append(renderTree(buildTree(exports), leaf => s"typeof ${leaf.fnName}"))
    sb.append(";\n")

    sb.toString()
  }

  private def tsTypeOf(tpe: AbiType): String = tpe match {
    case AbiType.Unit => "void"
    case AbiType.Bool => "boolean"
    case AbiType.Int8 | AbiType.Int16 | AbiType.Int32 | AbiType.Float32 | AbiType.Float64 => "number"
    case AbiType.Int64 => "bigint"
    case AbiType.String => "string"
    case AbiType.Bytes => "Uint8Array"
  }

  private def tsExecTypeOf(tpe: AbiType): String =
    s"TypedExports.api.${execTypeName(tpe)}"

  private def execTypeName(tpe: AbiType): String = tpe match {
    case AbiType.Unit => "ExecUnit"
    case AbiType.Bool => "ExecBool"
    case AbiType.Int8 => "ExecInt8"
    case AbiType.Int16 => "ExecInt16"
    case AbiType.Int32 => "ExecInt32"
    case AbiType.Int64 => "ExecInt64"
    case AbiType.Float32 => "ExecFloat32"
    case AbiType.Float64 => "ExecFloat64"
    case AbiType.String => "ExecString"
    case AbiType.Bytes => "ExecBytes"
  }

  private sealed trait ExportTree
  private case class ExportBranch(children: mutable.LinkedHashMap[String, ExportTree]) extends ExportTree
  private case class ExportLeaf(fnName: String) extends ExportTree

  private def buildTree(exports: List[LlvmWasmTypedExportsWriter.Entry]): ExportBranch = {
    val root = ExportBranch(mutable.LinkedHashMap.empty)

    exports.foreach { e =>
      val segments = symbolSegments(e.symbol)
      putLeaf(root, segments, ExportLeaf(flatFunctionName(e.symbol)))
      val resumeSegments = segments.init ::: List(s"resume${capitalize(segments.last)}")
      putLeaf(root, resumeSegments, ExportLeaf(flatResumeFunctionName(e.symbol)))
    }

    root
  }

  private def putLeaf(root: ExportBranch, segments: List[String], leaf: ExportLeaf): Unit = {
    var current = root
    segments.init.foreach { seg =>
      val next = current.children.getOrElseUpdate(seg, ExportBranch(mutable.LinkedHashMap.empty))
      current = next match {
        case branch: ExportBranch => branch
        case _: ExportLeaf =>
          throw InternalCompilerException(s"Invalid export symbol hierarchy for '${segments.mkString(".")}'.", ca.uwaterloo.flix.language.ast.SourceLocation.Unknown)
      }
    }
    current.children.put(segments.last, leaf)
  }

  private def renderTree(root: ExportBranch, renderLeaf: ExportLeaf => String): String = {
    def loop(branch: ExportBranch): String = {
      val body = branch.children.iterator.map {
        case (name, next: ExportBranch) =>
          s"${renderJsProperty(name)}: ${loop(next)}"
        case (name, leaf: ExportLeaf) =>
          s"${renderJsProperty(name)}: ${renderLeaf(leaf)}"
      }.mkString(", ")
      s"{ $body }"
    }

    loop(root)
  }

  private def flatFunctionName(sym: String): String =
    s"call_${mangleIdentifier(sym.replace('.', '_'))}"

  private def flatResumeFunctionName(sym: String): String =
    s"resume_${mangleIdentifier(sym.replace('.', '_'))}"

  private def symbolSegments(sym: String): List[String] =
    sym.split("\\.").toList.filter(_.nonEmpty)

  private def renderJsProperty(name: String): String =
    if (isValidJsIdentifier(name)) name else "\"" + escapeJsString(name) + "\""

  private def isValidJsIdentifier(s: String): Boolean =
    s.nonEmpty &&
      (s.head == '_' || s.head == '$' || s.head.isLetter) &&
      s.tail.forall(ch => ch == '_' || ch == '$' || ch.isLetterOrDigit)

  private def mangleIdentifier(s: String): String = {
    val b = new StringBuilder(s.length + 8)
    s.foreach {
      case c if c.isLetterOrDigit || c == '_' || c == '$' => b.append(c)
      case _ => b.append('_')
    }
    if (b.isEmpty) "_"
    else {
      val head = b.charAt(0)
      if (head.isDigit) "_" + b.toString() else b.toString()
    }
  }

  private def jsMethodNameFromWitName(name: String): String = {
    val parts = name.split("-").toList.filter(_.nonEmpty)
    parts match {
      case Nil => throw new IllegalStateException("empty wit name")
      case head :: tail => head + tail.map(capitalize).mkString
    }
  }

  private def capitalize(s: String): String =
    if (s.isEmpty) s else s"${s.head.toUpper}${s.tail}"

  private def escapeJsString(s: String): String = {
    val b = new StringBuilder(s.length + 8)
    s.foreach {
      case '"' => b.append("\\\"")
      case '\\' => b.append("\\\\")
      case '\b' => b.append("\\b")
      case '\f' => b.append("\\f")
      case '\n' => b.append("\\n")
      case '\r' => b.append("\\r")
      case '\t' => b.append("\\t")
      case c if c < ' ' => b.append(f"\\u${c.toInt}%04x")
      case c => b.append(c)
    }
    b.toString()
  }

  private def writeFile(path: Path, bytes: Array[Byte]): Unit = {
    Files.createDirectories(path.getParent)

    if (Files.exists(path)) {
      if (!Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS)) {
        throw InternalCompilerException(s"Unable to write to non-regular file: '$path'.", ca.uwaterloo.flix.language.ast.SourceLocation.Unknown)
      }
      if (!Files.isWritable(path)) {
        throw InternalCompilerException(s"Unable to write to read-only file: '$path'.", ca.uwaterloo.flix.language.ast.SourceLocation.Unknown)
      }
    }

    Files.write(path, bytes)
  }
}
