/*
 * Copyright 2026 Magnus Madsen
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ca.uwaterloo.flix.language.phase.llvm

import ca.uwaterloo.flix.api.Flix
import ca.uwaterloo.flix.language.ast.{LoweredAst, Symbol}
import ca.uwaterloo.flix.language.ast.SourceLocation
import ca.uwaterloo.flix.language.phase.ExportAbi
import ca.uwaterloo.flix.language.phase.ExportAbi.AbiType
import ca.uwaterloo.flix.util.{ArtifactNames, InternalCompilerException}

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, LinkOption, Path}

/**
  * Writes the public C header for LLVM-native exported functions (annotated with `@Export`).
  *
  * Public contract:
  *   - exported functions are typed C symbols with typed parameters,
  *   - normal returns are written through an explicit `out` pointer (except `Unit`),
  *   - the returned `flix_exec_t` reports `ok`, `thrown`, or `suspended`,
  *   - exceptions and suspensions cross the boundary as stable handles.
  */
object LlvmExportWriter {

  /**
    * Writes `outputPath/llvm/flix_exports.h` if there are exported definitions.
    *
    * Returns the path to the header (or `None` if there are no exports).
    */
  def run(root: LoweredAst.Root)(implicit flix: Flix): Option[Path] = {
    val exports = root.defs.values.toList.filter(_.ann.isExport).sortBy(_.sym.toString)
    if (exports.isEmpty) return None

    val header = renderHeader(exports)
    val bytes = header.getBytes(StandardCharsets.UTF_8)
    val path = exportsHeaderPath(flix.options.outputPath, flix.options.artifactName)
    writeFile(path, bytes)
    Some(path)
  }

  /**
    * Returns the location of the exports header for the current build.
    */
  def exportsHeaderPath(outputPath: Path, artifactName: String = ArtifactNames.DefaultBaseName): Path =
    outputPath.resolve("llvm/").resolve(ArtifactNames.nativeExportsHeaderFileName(artifactName)).toAbsolutePath

  private def renderHeader(exports: List[LoweredAst.Def]): String = {
    val sb = new StringBuilder(8 * 1024)

    sb.append("// Generated by the Flix compiler (LLVM-native)\n")
    sb.append("// NOTE: This public C ABI is experimental and may evolve while the native backend matures.\n")
    sb.append("\n")
    sb.append("#pragma once\n")
    sb.append("#include <stdint.h>\n")
    sb.append("#include <stdbool.h>\n")
    sb.append("#include <stddef.h>\n")
    sb.append("\n")
    sb.append("#ifdef __cplusplus\n")
    sb.append("extern \"C\" {\n")
    sb.append("#endif\n")
    sb.append("\n")
    sb.append("typedef struct flix_exec {\n")
    sb.append("  int64_t tag;\n")
    sb.append("  int64_t payload;\n")
    sb.append("} flix_exec_t;\n")
    sb.append("\n")
    sb.append("typedef struct flix_ctx flix_ctx_t;\n")
    sb.append("typedef int64_t flix_handle_t;\n")
    sb.append("typedef flix_handle_t flix_string_t;\n")
    sb.append("typedef flix_handle_t flix_bytes_t;\n")
    sb.append("typedef flix_handle_t flix_i8_array_t;\n")
    sb.append("\n")
    sb.append("enum {\n")
    sb.append("  FLIX_EXEC_OK = 1,\n")
    sb.append("  FLIX_EXEC_SUSPENDED = 3,\n")
    sb.append("  FLIX_EXEC_THROWN = 4,\n")
    sb.append("};\n")
    sb.append("\n")
    sb.append("void flix_init(int32_t argc, char** argv);\n")
    sb.append("flix_ctx_t* flix_ctx_new(void);\n")
    sb.append("void flix_ctx_free(flix_ctx_t* ctx);\n")
    sb.append("\n")
    sb.append("void flix_handle_retain(flix_ctx_t* ctx, flix_handle_t h);\n")
    sb.append("void flix_handle_release(flix_ctx_t* ctx, flix_handle_t h);\n")
    sb.append("flix_handle_t flix_handle_new_i64(flix_ctx_t* ctx, int64_t payload);\n")
    sb.append("int64_t flix_handle_unbox_i64(flix_ctx_t* ctx, flix_handle_t h);\n")
    sb.append("\n")
    sb.append("void flix_exn_report(flix_ctx_t* ctx, flix_handle_t exn);\n")
    sb.append("void flix_suspension_report(flix_ctx_t* ctx, flix_handle_t susp);\n")
    sb.append("int64_t flix_suspension_eff_sym_id(flix_ctx_t* ctx, flix_handle_t susp);\n")
    sb.append("int64_t flix_suspension_op_index(flix_ctx_t* ctx, flix_handle_t susp);\n")
    sb.append("int64_t flix_suspension_arg_count(flix_ctx_t* ctx, flix_handle_t susp);\n")
    sb.append("flix_handle_t flix_suspension_arg_as_i64(flix_ctx_t* ctx, flix_handle_t susp, int64_t idx);\n")
    sb.append("flix_handle_t flix_suspension_arg_as_ptr(flix_ctx_t* ctx, flix_handle_t susp, int64_t idx);\n")
    sb.append("void flix_free(void* ptr);\n")
    sb.append("\n")
    sb.append("flix_string_t flix_string_from_utf8(flix_ctx_t* ctx, const uint8_t* bytes, int64_t len);\n")
    sb.append("uint8_t* flix_string_to_utf8(flix_ctx_t* ctx, flix_string_t str, int64_t* out_len);\n")
    sb.append("\n")
    sb.append("flix_i8_array_t flix_i8_array_from_bytes(flix_ctx_t* ctx, const uint8_t* bytes, int64_t len);\n")
    sb.append("uint8_t* flix_i8_array_to_bytes(flix_ctx_t* ctx, flix_i8_array_t arr, int64_t* out_len);\n")
    sb.append("\n")
    sb.append("static inline flix_bytes_t flix_bytes_from_slice(flix_ctx_t* ctx, const uint8_t* bytes, int64_t len) {\n")
    sb.append("  return (flix_bytes_t)flix_i8_array_from_bytes(ctx, bytes, len);\n")
    sb.append("}\n")
    sb.append("\n")
    sb.append("static inline uint8_t* flix_bytes_to_slice(flix_ctx_t* ctx, flix_bytes_t bytes, int64_t* out_len) {\n")
    sb.append("  return flix_i8_array_to_bytes(ctx, (flix_i8_array_t)bytes, out_len);\n")
    sb.append("}\n")
    sb.append("\n")

    exports.foreach { defn =>
      val sig = defn.exportedSignature.getOrElse {
        throw InternalCompilerException(s"Missing portable export signature for '${defn.sym}'.", defn.loc)
      }
      val name = exportName(defn.sym)
      val resumeName = exportResumeName(defn.sym)
      val params = sig.params.zipWithIndex.map {
        case (tpe, i) => s", ${cTypeOf(tpe)} a$i"
      }.mkString
      val outParam = sig.result match {
        case AbiType.Unit => ""
        case other => s", ${cTypeOf(other)}* out"
      }
      sb.append(s"// ${defn.sym}\n")
      sb.append(s"// On FLIX_EXEC_OK, ${if (sig.result == AbiType.Unit) "the call completed normally." else "`*out` is initialized."}\n")
      sb.append(s"// On FLIX_EXEC_THROWN / FLIX_EXEC_SUSPENDED, `payload` is an exception/suspension handle.\n")
      sb.append(s"flix_exec_t $name(flix_ctx_t* ctx$params$outParam);\n\n")
      sb.append(s"// Resume for ${defn.sym} (after FLIX_EXEC_SUSPENDED)\n")
      sb.append(s"flix_exec_t $resumeName(flix_ctx_t* ctx, flix_handle_t susp, flix_handle_t resume$outParam);\n\n")
    }

    sb.append("#ifdef __cplusplus\n")
    sb.append("}\n")
    sb.append("#endif\n")

    sb.toString()
  }

  private def cTypeOf(tpe: AbiType): String = tpe match {
    case AbiType.Unit => "int64_t"
    case AbiType.Bool => "bool"
    case AbiType.Int8 => "int8_t"
    case AbiType.Int16 => "int16_t"
    case AbiType.Int32 => "int32_t"
    case AbiType.Int64 => "int64_t"
    case AbiType.Float32 => "float"
    case AbiType.Float64 => "double"
    case AbiType.String => "flix_string_t"
    case AbiType.Bytes => "flix_bytes_t"
  }

  private def exportName(sym: Symbol.DefnSym): String =
    s"flix_export_${mangle(sym.toString)}"

  private def exportResumeName(sym: Symbol.DefnSym): String =
    s"flix_export_resume_${mangle(sym.toString)}"

  /**
    * LLVM-safe name mangling: keep alphanumerics and `_`, replace everything else with `_`.
    */
  private def mangle(s: String): String = {
    val b = new StringBuilder(s.length + 8)
    s.foreach {
      case c if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' =>
        b.append(c)
      case _ => b.append('_')
    }
    if (b.isEmpty) "_"
    else {
      val head = b.charAt(0)
      if ((head >= '0' && head <= '9')) "_" + b.toString() else b.toString()
    }
  }

  private def writeFile(path: Path, bytes: Array[Byte]): Unit = {
    Files.createDirectories(path.getParent)

    if (Files.exists(path)) {
      if (!Files.isRegularFile(path, LinkOption.NOFOLLOW_LINKS)) {
        throw InternalCompilerException(s"Unable to write to non-regular file: '$path'.", SourceLocation.Unknown)
      }
      if (!Files.isWritable(path)) {
        throw InternalCompilerException(s"Unable to write to read-only file: '$path'.", SourceLocation.Unknown)
      }
      if (!(path.getFileName.toString.endsWith(".h"))) {
        throw InternalCompilerException(s"Refusing to overwrite non-.h file: '$path'.", SourceLocation.Unknown)
      }
    }

    Files.write(path, bytes)
  }

}
