[package]
name        = "flix"
description = "test"
version     = "0.1.0"
flix        = "0.68.0"
authors     = ["John Doe <john@example.com>"]

[build]
targets = ["jvm"]

[run]
target = "jvm"

[test]
target = "jvm"
